### ISSUE TITLE
Getting Rate Limit Exceeded Error

### ISSUE THREAD

**Issue by sandersio** [shadowban-eu/shadowban-eu-backend#2]
Hi Team,

I was able to setup and and run code on my local machine. However, when I deploy on Heroku, I am getting an error while acquiring guest token

`{'errors': [{'code': 88, 'message': 'Rate limit exceeded.'}]}
{'errors': [{'code': 88, 'message': 'Rate limit exceeded.'}]}`

**Comment by ghost** [comment]
This is an ip address limit. Your ip address (block) is probably shared with someone else scraping Twitter. Obtaining a dedicated ip address might help.
